name: Github Actions test

on: [push]

jobs:
  hello_world_job:
    runs-on: macos-latest
    name: Android UI Test
    steps:
      - uses: actions/checkout@v2
      # - uses: byunguk/action-runner@master
      #  with:
      #    api-version: 29
      - name: Install GPG
        run: sudo apt-get install gnupg2

      - name: Create keystore
        run: |
         echo ${{ secrets.KEYSTORE_BASE64 }} > leia.jks.asc
