name: Github Actions test

on: [push]

jobs:
  hello_world_job:
    runs-on: macos-latest
    name: Android UI Test
    steps:
    - uses: actions/checkout@v2
    - uses: byunguk/action-runner@master
      with:
        api-version: '29'
