name: Github Actions test

on: [push]

jobs:
  hello_world_job:
    runs-on: macos-latest
    name: Android UI Test
    steps:
      - uses: byunguk/action-runner@master
        with:
          api-version: 29
      #- name: Install GPG
      #  run: npm install -g gpg

