name: Github Actions Test

on: [push]

jobs:
  hello_world_job:
    runs-on: macos-latest
    name: Android UI Test
    steps:
      - name: Dump github context
        run: echo "$GITHUB_CONTEXT"
        shell: bash
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - uses: byunguk/action-runner@master
        with:
          api-version: '29'
      #- name: Install GPG
      #  run: npm install -g gpg

